@startuml UseCase Gioco Poker

actor Player as P

rectangle "Azioni del Giocatore" {
  usecase "Fare una scommessa" as Bet
  usecase "Rilanciare" as Raise
  usecase "Passare" as Fold
  usecase "Mostrare le carte" as ShowCards
  usecase "Confronto" as Comparison
  usecase "Menu" as Menu
}

rectangle {
  usecase "Abbandonare la partita" as Quit
  usecase "Comunicare" as Communication
  usecase "Consultare le regole" as Rules
}

P --> Bet
P --> Raise
P --> Fold
P --> ShowCards
P --> Comparison
P --> Menu

Menu --> Rules
Menu --> Communication
Menu --> Quit

@enduml
