@startuml Diagramma delle Sequenze client-server
!define SERVER class

actor Player as P
participant Server as S

P --> Bet : "Fare una scommessa"
P --> Fold : "Passare"
P --> Menu : "Menu"

Menu --> Rules : "Consultare le regole"
Menu --> Quit : "Abbandonare la partita"

P --> S : "Invia Richiesta"
S --> P : "Risposta del Server"

@enduml
