@startuml UseCase Gioco Poker Lato Client

actor Player as P

rectangle "Azioni del Giocatore" {
  usecase "Fare una scommessa" as Bet
  usecase "Passare" as Fold
  usecase "Menu" as Menu
}

rectangle {
  usecase "Abbandonare la partita" as Quit
  usecase "Comunicare" as Communication
  usecase "Consultare le regole" as Rules
}

P --> Bet
P --> Fold
P --> Menu

Menu --> Rules
Menu --> Communication
Menu --> Quit

@enduml
